# Generated by Django 5.1.5 on 2025-05-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlyBCn',
            fields=[
                ('my_gstin', models.CharField(db_column='My GSTIN', max_length=15)),
                ('gstin_of_supplier', models.CharField(db_column='GSTIN of Supplier', max_length=15, primary_key=True, serialize=False)),
                ('supplier_trade_name', models.CharField(db_column='Supplier Trade Name', max_length=255)),
                ('invoice_number', models.CharField(db_column='Note/Refund Voucher Number', max_length=50)),
                ('invoice_date', models.DateField(db_column='Note/Refund Voucher date')),
                ('taxable_value', models.DecimalField(db_column='Taxable Value', decimal_places=2, max_digits=12)),
                ('integrated_tax_paid', models.DecimalField(db_column='Integrated Tax Paid', decimal_places=2, max_digits=12)),
                ('centralstate_tax_paid', models.DecimalField(db_column='CentralState_Tax_Paid', decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'only_b_cn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnlyBDn',
            fields=[
                ('my_gstin', models.CharField(db_column='My GSTIN', max_length=15)),
                ('gstin_of_supplier', models.CharField(db_column='GSTIN of Supplier', max_length=15, primary_key=True, serialize=False)),
                ('supplier_trade_name', models.CharField(db_column='Supplier Trade Name', max_length=255)),
                ('invoice_number', models.CharField(db_column='Note/Refund Voucher Number', max_length=50)),
                ('invoice_date', models.DateField(db_column='Note/Refund Voucher date')),
                ('taxable_value', models.DecimalField(db_column='Taxable Value', decimal_places=2, max_digits=12)),
                ('integrated_tax_paid', models.DecimalField(db_column='Integrated Tax Paid', decimal_places=2, max_digits=12)),
                ('centralstate_tax_paid', models.DecimalField(db_column='CentralState_Tax_Paid', decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'only_b_dn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnlyBInv',
            fields=[
                ('my_gstin', models.CharField(db_column='My GSTIN', max_length=15)),
                ('gstin_of_supplier', models.CharField(db_column='GSTIN of Supplier', max_length=15, primary_key=True, serialize=False)),
                ('supplier_trade_name', models.CharField(db_column='Supplier Trade Name', max_length=255)),
                ('invoice_number', models.CharField(db_column='Invoice Number', max_length=50)),
                ('invoice_date', models.DateField(db_column='Invoice date')),
                ('taxable_value', models.DecimalField(db_column='Taxable Value', decimal_places=2, max_digits=12)),
                ('integrated_tax_paid', models.DecimalField(db_column='Integrated Tax Paid', decimal_places=2, max_digits=12)),
                ('centralstate_tax_paid', models.DecimalField(db_column='CentralState_Tax_Paid', decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'only_b_inv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnlyPCn',
            fields=[
                ('my_gstin', models.CharField(db_column='My GSTIN', max_length=15)),
                ('supplier_gstin', models.CharField(db_column='Supplier GSTIN', max_length=15, primary_key=True, serialize=False)),
                ('supplier_trade_name', models.CharField(db_column='Supplier Trade Name', max_length=255)),
                ('document_number', models.CharField(db_column='Document Number', max_length=50)),
                ('document_date', models.DateField(db_column='Document Date')),
                ('total_taxable_value', models.DecimalField(db_column='Total Taxable Value', decimal_places=2, max_digits=12)),
                ('igst_amount', models.DecimalField(db_column='IGST Amount', decimal_places=2, max_digits=12)),
                ('cs_gst_amount', models.DecimalField(db_column='CS_GST_Amount', decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'only_p_cn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnlyPDn',
            fields=[
                ('my_gstin', models.CharField(db_column='My GSTIN', max_length=15)),
                ('supplier_gstin', models.CharField(db_column='Supplier GSTIN', max_length=15, primary_key=True, serialize=False)),
                ('supplier_trade_name', models.CharField(db_column='Supplier Trade Name', max_length=255)),
                ('document_number', models.CharField(db_column='Document Number', max_length=50)),
                ('document_date', models.DateField(db_column='Document Date')),
                ('total_taxable_value', models.DecimalField(db_column='Total Taxable Value', decimal_places=2, max_digits=12)),
                ('igst_amount', models.DecimalField(db_column='IGST Amount', decimal_places=2, max_digits=12)),
                ('cs_gst_amount', models.DecimalField(db_column='CS_GST_Amount', decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'only_p_dn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnlyPInv',
            fields=[
                ('my_gstin', models.CharField(db_column='My GSTIN', max_length=15)),
                ('supplier_gstin', models.CharField(db_column='Supplier GSTIN', max_length=15, primary_key=True, serialize=False)),
                ('supplier_trade_name', models.CharField(db_column='Supplier Trade Name', max_length=255)),
                ('document_number', models.CharField(db_column='Document Number', max_length=50)),
                ('document_date', models.DateField(db_column='Document Date')),
                ('total_taxable_value', models.DecimalField(db_column='Total Taxable Value', decimal_places=2, max_digits=12)),
                ('igst_amount', models.DecimalField(db_column='IGST Amount', decimal_places=2, max_digits=12)),
                ('cs_gst_amount', models.DecimalField(db_column='CS_GST_Amount', decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'only_p_inv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
