# Generated by Django 5.2 on 2025-05-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('gstin', models.CharField(db_column='GSTIN', max_length=15, primary_key=True, serialize=False)),
                ('trader_name', models.CharField(db_column='Trader Name', max_length=255)),
                ('legal_name', models.CharField(db_column='Legal Name', max_length=255)),
                ('group', models.CharField(db_column='Group', max_length=100)),
                ('contact_person_name', models.CharField(db_column='Contact Person Name', max_length=255)),
                ('mo', models.CharField(db_column='Mo', max_length=15)),
            ],
            options={
                'db_table': 'list',
            },
        ),
    ]
